alerts:
  slack:
    channel: C06617RUDV4
    token: Bearer xoxb-...
queue:
  redis:
    host: localhost
    port: 6379
    channel: sensors-alerts
sensors:
  - name: TemperatureSensor
    enabled: true
    validRange:
      min: 0
      max: 100
  - name: HumiditySensor
    enabled: true
    validRange:
      min: 0
      max: 100
  - name: PressureSensor
    enabled: true
    validRange:
      min: 0
      max: 20